language: php
git:
    submodules: false
php:
- 5.6
- hhvm
services:
  - mysql

before_install:
- 'php -S 127.0.0.1:9999 > /tmp/server.log 2>&1 &'

before_script:
- cp .env.travis .env
- mysql -e 'create database oscillo_test;'
- composer self-update
- composer install
- php artisan migrate
- chmod -R 777 storage

addons:
    code_climate:
        repo_token: a413b6a8438597fbf5bc7db30e4068be8e15a60b439117fd86284bb01905a107
script:
- phpunit

notifications:
  emails:
  - dokumegane@interestic.com
