language: php
git:
    submodules: false
php:
- 5.6
- hhvm
before_script:
- composer self-update
- composer install
- chmod -R 777 storage
script:
- phpunit
notifications:
  emails:
  - dokumegane@interestic.com
