language: php
git:
    submodules: false
php:
- 5.6
- hhvm
services:
  - mysql

before_install:
- 'php -S 127.0.0.1:9999 > /tmp/server.log 2>&1 &'

before_script:
- cp .env.travis .env
- mysql -e 'create database oscillo_test;'
- php artisan migrate
- php artisan batch:owm import-city
- composer self-update
- composer install
- chmod -R 777 storage

script:
- phpunit

notifications:
  emails:
  - dokumegane@interestic.com
