language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install
  - chmod -R 777 app/storage

before_install:
  - openssl aes-256-cbc -K $encrypted_80a506355ae3_key -iv $encrypted_80a506355ae3_iv -in travis_rsa.enc -out ~\/.ssh/travis_rsa -d
  - cp .travis_rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - phpunit

notifications:
  emails:
    - dokumegane@interestic.com