language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install
  - chmod -R 777 app/storage

script:
  - phpunit

notifications:
  emails:
    - dokumegane@interestic.com